# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-24 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remaining', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BooksDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('isIssued', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Book')),
            ],
        ),
        migrations.CreateModel(
            name='IssueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('books_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.BooksDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollnumber', models.CharField(max_length=50, unique=True)),
                ('uniqueCode', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnDate', models.DateTimeField()),
                ('gThan', models.IntegerField(default=0)),
                ('lThan', models.IntegerField(default=1000000000)),
            ],
        ),
        migrations.AddField(
            model_name='issuedetail',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Member'),
        ),
    ]
